table FactVentas
	lineageTag: fact-ventas-01

	column VentaID
		dataType: int64
		formatString: 0
		lineageTag: fv-col-01
		summarizeBy: none
		sourceColumn: VentaID

		annotation SummarizationSetBy = Automatic

	column FechaID
		dataType: int64
		formatString: 0
		lineageTag: fv-col-02
		summarizeBy: none
		sourceColumn: FechaID

		annotation SummarizationSetBy = Automatic

	column CategoriaID
		dataType: int64
		formatString: 0
		lineageTag: fv-col-03
		summarizeBy: none
		sourceColumn: CategoriaID

		annotation SummarizationSetBy = Automatic

	column Ingresos
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: fv-col-04
		summarizeBy: sum
		sourceColumn: Ingresos

		annotation SummarizationSetBy = Automatic

	column Unidades
		dataType: int64
		formatString: #,0
		lineageTag: fv-col-05
		summarizeBy: sum
		sourceColumn: Unidades

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: fv-col-06
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	partition FactVentas-Partition = m
		mode: import
		source =
				let
				    Semilla = {
				        {20230101, 5, 86118, 9, "Norte"},
				        {20230101, 1, 248895, 20, "Norte"},
				        {20230101, 3, 124526, 27, "Sur"},
				        {20230101, 5, 65248, 11, "Sur"},
				        {20230101, 2, 129762, 13, "Sur"},
				        {20230101, 4, 119399, 32, "Centro"},
				        {20230101, 5, 97758, 9, "Centro"},
				        {20230101, 3, 210564, 26, "Centro"},
				        {20230201, 3, 222342, 23, "Norte"},
				        {20230201, 2, 150495, 12, "Norte"},
				        {20230201, 5, 69252, 9, "Norte"},
				        {20230201, 2, 122882, 13, "Sur"},
				        {20230201, 1, 163219, 17, "Sur"},
				        {20230201, 4, 95588, 34, "Centro"},
				        {20230201, 1, 249164, 17, "Centro"},
				        {20230201, 5, 83253, 10, "Centro"},
				        {20230301, 1, 263869, 18, "Norte"},
				        {20230301, 4, 109618, 36, "Norte"},
				        {20230301, 5, 83277, 9, "Norte"},
				        {20230301, 1, 225459, 19, "Sur"},
				        {20230301, 5, 78193, 11, "Sur"},
				        {20230301, 2, 147699, 11, "Sur"},
				        {20230301, 4, 125672, 37, "Centro"},
				        {20230301, 2, 185448, 11, "Centro"},
				        {20230301, 5, 102552, 9, "Centro"},
				        {20230401, 5, 87787, 11, "Norte"},
				        {20230401, 4, 108782, 40, "Norte"},
				        {20230401, 2, 208362, 13, "Norte"},
				        {20230401, 3, 171449, 26, "Sur"},
				        {20230401, 5, 55199, 11, "Sur"},
				        {20230401, 3, 262575, 25, "Centro"},
				        {20230401, 2, 205745, 10, "Centro"},
				        {20230501, 1, 268418, 19, "Norte"},
				        {20230501, 3, 219815, 22, "Norte"},
				        {20230501, 2, 208194, 10, "Norte"},
				        {20230501, 5, 58872, 10, "Sur"},
				        {20230501, 3, 174578, 26, "Sur"},
				        {20230501, 5, 98675, 9, "Centro"},
				        {20230501, 3, 258448, 22, "Centro"},
				        {20230501, 2, 231617, 13, "Centro"},
				        {20230601, 3, 247448, 25, "Norte"},
				        {20230601, 5, 96754, 9, "Norte"},
				        {20230601, 4, 109315, 38, "Norte"},
				        {20230601, 3, 184628, 22, "Sur"},
				        {20230601, 5, 83685, 11, "Sur"},
				        {20230601, 3, 246852, 23, "Centro"},
				        {20230601, 5, 116186, 9, "Centro"},
				        {20230601, 1, 302624, 20, "Centro"},
				        {20230701, 1, 264655, 21, "Norte"},
				        {20230701, 4, 89456, 34, "Norte"},
				        {20230701, 2, 126397, 11, "Sur"},
				        {20230701, 1, 188616, 15, "Sur"},
				        {20230701, 3, 202164, 25, "Centro"},
				        {20230701, 4, 102346, 31, "Centro"},
				        {20230701, 5, 94789, 10, "Centro"},
				        {20230801, 2, 186492, 14, "Norte"},
				        {20230801, 1, 205692, 16, "Norte"},
				        {20230801, 4, 84552, 32, "Sur"},
				        {20230801, 5, 51219, 11, "Sur"},
				        {20230801, 2, 184664, 11, "Centro"},
				        {20230801, 5, 91472, 10, "Centro"},
				        {20230801, 3, 236417, 23, "Centro"},
				        {20230901, 3, 264727, 22, "Norte"},
				        {20230901, 5, 87533, 10, "Norte"},
				        {20230901, 4, 93793, 31, "Sur"},
				        {20230901, 3, 160173, 22, "Sur"},
				        {20230901, 2, 165132, 13, "Sur"},
				        {20230901, 3, 284493, 27, "Centro"},
				        {20230901, 2, 244518, 13, "Centro"},
				        {20230901, 1, 295669, 16, "Centro"},
				        {20231001, 1, 334115, 16, "Norte"},
				        {20231001, 5, 103874, 11, "Norte"},
				        {20231001, 3, 185624, 24, "Sur"},
				        {20231001, 2, 161654, 11, "Sur"},
				        {20231001, 1, 218854, 20, "Sur"},
				        {20231001, 2, 235383, 12, "Centro"},
				        {20231001, 3, 294398, 27, "Centro"},
				        {20231001, 1, 374132, 17, "Centro"},
				        {20231101, 1, 311382, 16, "Norte"},
				        {20231101, 4, 120297, 39, "Norte"},
				        {20231101, 3, 203528, 25, "Sur"},
				        {20231101, 5, 82245, 9, "Sur"},
				        {20231101, 5, 120871, 9, "Centro"},
				        {20231101, 4, 132836, 32, "Centro"},
				        {20231101, 3, 265329, 21, "Centro"},
				        {20231201, 1, 408558, 19, "Norte"},
				        {20231201, 3, 256383, 22, "Norte"},
				        {20231201, 4, 164533, 35, "Norte"},
				        {20231201, 4, 120244, 36, "Sur"},
				        {20231201, 2, 225727, 11, "Sur"},
				        {20231201, 3, 328451, 23, "Centro"},
				        {20231201, 1, 429794, 19, "Centro"},
				        {20240101, 5, 102133, 12, "Norte"},
				        {20240101, 3, 207621, 29, "Norte"},
				        {20240101, 4, 111685, 40, "Norte"},
				        {20240101, 1, 194498, 18, "Sur"},
				        {20240101, 4, 84593, 41, "Sur"},
				        {20240101, 2, 184372, 12, "Centro"},
				        {20240101, 3, 266173, 31, "Centro"},
				        {20240201, 1, 298465, 21, "Norte"},
				        {20240201, 2, 209258, 15, "Norte"},
				        {20240201, 3, 182871, 32, "Sur"},
				        {20240201, 1, 189237, 22, "Sur"},
				        {20240201, 2, 145523, 14, "Sur"},
				        {20240201, 1, 289285, 20, "Centro"},
				        {20240201, 3, 227535, 26, "Centro"},
				        {20240301, 3, 286345, 31, "Norte"},
				        {20240301, 1, 293383, 21, "Norte"},
				        {20240301, 3, 210863, 30, "Sur"},
				        {20240301, 2, 191151, 13, "Sur"},
				        {20240301, 4, 106642, 37, "Sur"},
				        {20240301, 4, 148141, 38, "Centro"},
				        {20240301, 2, 284884, 14, "Centro"},
				        {20240301, 5, 106847, 12, "Centro"},
				        {20240401, 2, 191476, 13, "Norte"},
				        {20240401, 1, 312548, 20, "Norte"},
				        {20240401, 4, 106659, 44, "Sur"},
				        {20240401, 2, 140875, 14, "Sur"},
				        {20240401, 5, 120643, 12, "Centro"},
				        {20240401, 3, 286412, 29, "Centro"},
				        {20240501, 5, 99232, 13, "Norte"},
				        {20240501, 2, 205181, 13, "Norte"},
				        {20240501, 4, 134779, 43, "Norte"},
				        {20240501, 1, 244473, 23, "Sur"},
				        {20240501, 3, 185517, 30, "Sur"},
				        {20240501, 2, 187249, 12, "Sur"},
				        {20240501, 3, 306332, 26, "Centro"},
				        {20240501, 1, 355714, 22, "Centro"},
				        {20240601, 5, 126629, 11, "Norte"},
				        {20240601, 2, 248457, 12, "Norte"},
				        {20240601, 4, 153355, 48, "Norte"},
				        {20240601, 5, 79157, 11, "Sur"},
				        {20240601, 3, 234621, 24, "Sur"},
				        {20240601, 5, 144782, 12, "Centro"},
				        {20240601, 4, 179539, 47, "Centro"},
				        {20240601, 2, 274878, 13, "Centro"},
				        {20240701, 2, 213318, 15, "Norte"},
				        {20240701, 4, 132891, 48, "Norte"},
				        {20240701, 3, 185274, 31, "Sur"},
				        {20240701, 1, 218452, 19, "Sur"},
				        {20240701, 2, 164488, 16, "Sur"},
				        {20240701, 4, 134281, 47, "Centro"},
				        {20240701, 2, 231793, 15, "Centro"},
				        {20240801, 5, 93541, 12, "Norte"},
				        {20240801, 1, 317241, 20, "Norte"},
				        {20240801, 2, 131851, 13, "Sur"},
				        {20240801, 4, 104599, 48, "Sur"},
				        {20240801, 1, 220456, 23, "Sur"},
				        {20240801, 3, 243376, 32, "Centro"},
				        {20240801, 2, 192751, 15, "Centro"},
				        {20240901, 4, 121485, 37, "Norte"},
				        {20240901, 1, 376863, 21, "Norte"},
				        {20240901, 5, 93658, 12, "Sur"},
				        {20240901, 4, 109449, 49, "Sur"},
				        {20240901, 2, 196643, 13, "Sur"},
				        {20240901, 1, 366214, 20, "Centro"},
				        {20240901, 3, 302153, 27, "Centro"},
				        {20241001, 4, 163415, 43, "Norte"},
				        {20241001, 2, 217312, 12, "Norte"},
				        {20241001, 1, 323136, 20, "Norte"},
				        {20241001, 3, 234712, 29, "Sur"},
				        {20241001, 4, 112863, 41, "Sur"},
				        {20241001, 2, 247195, 13, "Centro"},
				        {20241001, 5, 150333, 13, "Centro"},
				        {20241101, 3, 343112, 27, "Norte"},
				        {20241101, 2, 291496, 16, "Norte"},
				        {20241101, 4, 155165, 47, "Norte"},
				        {20241101, 5, 94627, 13, "Sur"},
				        {20241101, 3, 254585, 26, "Sur"},
				        {20241101, 1, 267569, 22, "Sur"},
				        {20241101, 3, 366646, 30, "Centro"},
				        {20241101, 5, 132186, 13, "Centro"},
				        {20241101, 2, 276378, 16, "Centro"},
				        {20241201, 5, 161171, 12, "Norte"},
				        {20241201, 4, 181638, 39, "Norte"},
				        {20241201, 2, 197824, 16, "Sur"},
				        {20241201, 1, 319841, 19, "Sur"},
				        {20241201, 4, 169686, 42, "Centro"},
				        {20241201, 3, 415527, 31, "Centro"},
				        {20250101, 3, 301233, 35, "Norte"},
				        {20250101, 1, 263324, 21, "Norte"},
				        {20250101, 4, 115543, 52, "Norte"},
				        {20250101, 4, 89864, 51, "Sur"},
				        {20250101, 5, 76611, 12, "Sur"},
				        {20250101, 2, 238579, 15, "Centro"},
				        {20250101, 1, 323755, 24, "Centro"},
				        {20250101, 3, 246118, 32, "Centro"},
				        {20250201, 3, 251116, 32, "Norte"},
				        {20250201, 1, 342217, 25, "Norte"},
				        {20250201, 5, 118288, 16, "Norte"},
				        {20250201, 1, 215124, 23, "Sur"},
				        {20250201, 5, 84468, 13, "Sur"},
				        {20250201, 2, 203239, 17, "Sur"},
				        {20250201, 1, 374393, 28, "Centro"},
				        {20250201, 5, 137345, 13, "Centro"},
				        {20250201, 2, 291241, 18, "Centro"},
				        {20250301, 2, 295517, 19, "Norte"},
				        {20250301, 4, 134137, 43, "Norte"},
				        {20250301, 3, 287481, 30, "Norte"},
				        {20250301, 1, 242791, 28, "Sur"},
				        {20250301, 5, 80481, 15, "Sur"},
				        {20250301, 2, 322299, 18, "Centro"},
				        {20250301, 1, 385547, 28, "Centro"},
				        {20250301, 3, 364472, 36, "Centro"},
				        {20250401, 5, 123419, 14, "Norte"},
				        {20250401, 2, 259637, 15, "Norte"},
				        {20250401, 1, 361836, 24, "Norte"},
				        {20250401, 2, 172294, 18, "Sur"},
				        {20250401, 5, 101891, 12, "Sur"},
				        {20250401, 1, 415126, 28, "Centro"},
				        {20250401, 4, 182369, 51, "Centro"},
				        {20250401, 2, 273157, 14, "Centro"},
				        {20250501, 5, 113476, 14, "Norte"},
				        {20250501, 3, 343526, 35, "Norte"},
				        {20250501, 4, 172368, 49, "Norte"},
				        {20250501, 1, 305435, 24, "Sur"},
				        {20250501, 5, 101211, 14, "Sur"},
				        {20250501, 3, 357441, 32, "Centro"},
				        {20250501, 5, 147886, 15, "Centro"},
				        {20250501, 4, 190168, 55, "Centro"},
				        {20250601, 1, 464131, 24, "Norte"},
				        {20250601, 3, 335732, 34, "Norte"},
				        {20250601, 2, 246491, 18, "Sur"},
				        {20250601, 5, 104459, 13, "Sur"},
				        {20250601, 1, 374187, 28, "Centro"},
				        {20250601, 5, 142593, 14, "Centro"},
				        {20250701, 1, 363378, 23, "Norte"},
				        {20250701, 3, 320634, 29, "Norte"},
				        {20250701, 2, 181361, 15, "Sur"},
				        {20250701, 3, 240846, 36, "Sur"},
				        {20250701, 5, 92345, 15, "Sur"},
				        {20250701, 2, 285581, 15, "Centro"},
				        {20250701, 3, 301786, 36, "Centro"},
				        {20250801, 1, 324318, 23, "Norte"},
				        {20250801, 3, 259852, 37, "Norte"},
				        {20250801, 5, 107638, 14, "Norte"},
				        {20250801, 2, 192595, 19, "Sur"},
				        {20250801, 5, 75598, 13, "Sur"},
				        {20250801, 4, 156385, 55, "Centro"},
				        {20250801, 3, 315541, 36, "Centro"},
				        {20250801, 2, 224223, 15, "Centro"},
				        {20250901, 5, 139442, 13, "Norte"},
				        {20250901, 3, 312858, 33, "Norte"},
				        {20250901, 5, 94522, 14, "Sur"},
				        {20250901, 4, 106712, 50, "Sur"},
				        {20250901, 2, 308468, 16, "Centro"},
				        {20250901, 1, 474752, 22, "Centro"},
				        {20251001, 4, 161474, 50, "Norte"},
				        {20251001, 2, 306387, 19, "Norte"},
				        {20251001, 3, 373381, 31, "Norte"},
				        {20251001, 5, 110695, 16, "Sur"},
				        {20251001, 3, 286745, 35, "Sur"},
				        {20251001, 2, 319779, 15, "Centro"},
				        {20251001, 3, 345642, 30, "Centro"},
				        {20251101, 5, 143666, 15, "Norte"},
				        {20251101, 3, 412468, 30, "Norte"},
				        {20251101, 1, 447732, 25, "Norte"},
				        {20251101, 3, 278535, 32, "Sur"},
				        {20251101, 4, 167573, 47, "Sur"},
				        {20251101, 1, 450236, 22, "Centro"},
				        {20251101, 2, 334197, 14, "Centro"},
				        {20251201, 3, 406349, 29, "Norte"},
				        {20251201, 4, 183758, 50, "Norte"},
				        {20251201, 3, 345812, 35, "Sur"},
				        {20251201, 5, 125332, 15, "Sur"},
				        {20251201, 3, 447313, 36, "Centro"},
				        {20251201, 4, 228721, 54, "Centro"}
				    },
				    Tabla = Table.FromRows(Semilla, {"FechaID", "CategoriaID", "Ingresos", "Unidades", "Region"}),
				    ConID = Table.AddIndexColumn(Tabla, "VentaID", 1, 1, Int64.Type),
				    Tipado = Table.TransformColumnTypes(ConID, {
				        {"FechaID",     Int64.Type},
				        {"CategoriaID", Int64.Type},
				        {"Ingresos",    type number},
				        {"Unidades",    Int64.Type},
				        {"Region",      type text}
				    })
				in
				    Tipado

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

