table FactGastos
	lineageTag: fact-gastos-01

	column GastoID
		dataType: int64
		formatString: 0
		lineageTag: fg-col-01
		summarizeBy: none
		sourceColumn: GastoID

		annotation SummarizationSetBy = Automatic

	column FechaID
		dataType: int64
		formatString: 0
		lineageTag: fg-col-02
		summarizeBy: none
		sourceColumn: FechaID

		annotation SummarizationSetBy = Automatic

	column CategoriaID
		dataType: int64
		formatString: 0
		lineageTag: fg-col-03
		summarizeBy: none
		sourceColumn: CategoriaID

		annotation SummarizationSetBy = Automatic

	column Gastos
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: fg-col-04
		summarizeBy: sum
		sourceColumn: Gastos

		annotation SummarizationSetBy = Automatic

	column Presupuesto
		dataType: double
		formatString: \$#,0.00;(\$#,0.00)
		lineageTag: fg-col-05
		summarizeBy: sum
		sourceColumn: Presupuesto

		annotation SummarizationSetBy = Automatic

	partition FactGastos-Partition = m
		mode: import
		source =
				let
				    Semilla = {
				        {20230101, 6, 109555, 117336},
				        {20230101, 7, 51815, 54877},
				        {20230101, 8, 39552, 44118},
				        {20230101, 9, 29223, 29873},
				        {20230101, 10, 31218, 38834},
				        {20230201, 6, 115418, 119278},
				        {20230201, 7, 53253, 54743},
				        {20230201, 8, 47572, 45714},
				        {20230201, 9, 28424, 29634},
				        {20230201, 10, 46467, 39241},
				        {20230301, 6, 125332, 126198},
				        {20230301, 7, 60399, 58112},
				        {20230301, 8, 44477, 47591},
				        {20230301, 9, 33149, 31156},
				        {20230301, 10, 56168, 41426},
				        {20230401, 6, 119213, 122158},
				        {20230401, 7, 51452, 56526},
				        {20230401, 8, 59519, 46516},
				        {20230401, 9, 32823, 30539},
				        {20230401, 10, 38412, 40666},
				        {20230501, 6, 127342, 125124},
				        {20230501, 7, 64186, 57695},
				        {20230501, 8, 49385, 47199},
				        {20230501, 9, 33593, 31495},
				        {20230501, 10, 39899, 41718},
				        {20230601, 6, 133373, 130325},
				        {20230601, 7, 57678, 59848},
				        {20230601, 8, 41272, 49767},
				        {20230601, 9, 32886, 32795},
				        {20230601, 10, 50662, 43569},
				        {20230701, 6, 112439, 120847},
				        {20230701, 7, 52359, 55475},
				        {20230701, 8, 39377, 45221},
				        {20230701, 9, 29764, 30295},
				        {20230701, 10, 31369, 39594},
				        {20230801, 6, 117237, 120298},
				        {20230801, 7, 53476, 55214},
				        {20230801, 8, 56454, 45584},
				        {20230801, 9, 28767, 30237},
				        {20230801, 10, 46311, 39229},
				        {20230901, 6, 128892, 127831},
				        {20230901, 7, 64184, 58521},
				        {20230901, 8, 36658, 48219},
				        {20230901, 9, 32814, 31519},
				        {20230901, 10, 44652, 42449},
				        {20231001, 6, 132235, 132346},
				        {20231001, 7, 64137, 60776},
				        {20231001, 8, 66236, 50791},
				        {20231001, 9, 36671, 33713},
				        {20231001, 10, 40534, 43311},
				        {20231101, 6, 130345, 137538},
				        {20231101, 7, 68468, 63837},
				        {20231101, 8, 54355, 52887},
				        {20231101, 9, 34654, 34545},
				        {20231101, 10, 36645, 45465},
				        {20231201, 6, 176618, 143432},
				        {20231201, 7, 59323, 65259},
				        {20231201, 8, 61893, 54244},
				        {20231201, 9, 38617, 35549},
				        {20231201, 10, 42637, 47635},
				        {20240101, 6, 127766, 129255},
				        {20240101, 7, 57224, 61455},
				        {20240101, 8, 46737, 49322},
				        {20240101, 9, 28321, 31128},
				        {20240101, 10, 51756, 43844},
				        {20240201, 6, 128862, 131389},
				        {20240201, 7, 70135, 62553},
				        {20240201, 8, 36318, 50734},
				        {20240201, 9, 30165, 31462},
				        {20240201, 10, 46373, 44415},
				        {20240301, 6, 140669, 139131},
				        {20240301, 7, 73153, 66165},
				        {20240301, 8, 54285, 53712},
				        {20240301, 9, 31468, 33888},
				        {20240301, 10, 55127, 46382},
				        {20240401, 6, 133187, 134437},
				        {20240401, 7, 56131, 64563},
				        {20240401, 8, 66481, 52146},
				        {20240401, 9, 35722, 32421},
				        {20240401, 10, 41751, 45348},
				        {20240501, 6, 149272, 138144},
				        {20240501, 7, 63474, 65155},
				        {20240501, 8, 48166, 53662},
				        {20240501, 9, 34253, 33569},
				        {20240501, 10, 51813, 46652},
				        {20240601, 6, 133693, 143831},
				        {20240601, 7, 66774, 68464},
				        {20240601, 8, 70647, 55867},
				        {20240601, 9, 32899, 34345},
				        {20240601, 10, 54325, 48633},
				        {20240701, 6, 137144, 132327},
				        {20240701, 7, 67885, 63351},
				        {20240701, 8, 56853, 51757},
				        {20240701, 9, 30337, 31756},
				        {20240701, 10, 46484, 44628},
				        {20240801, 6, 142737, 132297},
				        {20240801, 7, 55751, 62551},
				        {20240801, 8, 54634, 50268},
				        {20240801, 9, 25477, 31725},
				        {20240801, 10, 35515, 44236},
				        {20240901, 6, 135162, 140616},
				        {20240901, 7, 73565, 67753},
				        {20240901, 8, 58717, 54895},
				        {20240901, 9, 34214, 33824},
				        {20240901, 10, 46553, 47144},
				        {20241001, 6, 149537, 145435},
				        {20241001, 7, 61329, 69339},
				        {20241001, 8, 51886, 56422},
				        {20241001, 9, 35277, 35637},
				        {20241001, 10, 41631, 49388},
				        {20241101, 6, 156813, 151896},
				        {20241101, 7, 78259, 71556},
				        {20241101, 8, 78166, 58426},
				        {20241101, 9, 36394, 36277},
				        {20241101, 10, 59286, 50811},
				        {20241201, 6, 189749, 157365},
				        {20241201, 7, 71689, 75622},
				        {20241201, 8, 63247, 60428},
				        {20241201, 9, 34496, 37188},
				        {20241201, 10, 56531, 53866},
				        {20250101, 6, 138673, 142822},
				        {20250101, 7, 62856, 70355},
				        {20250101, 8, 53799, 55325},
				        {20250101, 9, 33544, 33672},
				        {20250101, 10, 49182, 48667},
				        {20250201, 6, 149345, 144366},
				        {20250201, 7, 69495, 71138},
				        {20250201, 8, 49417, 56216},
				        {20250201, 9, 32892, 33792},
				        {20250201, 10, 51558, 49576},
				        {20250301, 6, 154445, 153691},
				        {20250301, 7, 73582, 75146},
				        {20250301, 8, 71647, 60215},
				        {20250301, 9, 35544, 35445},
				        {20250301, 10, 61278, 52735},
				        {20250401, 6, 152531, 148764},
				        {20250401, 7, 64694, 73868},
				        {20250401, 8, 41518, 58713},
				        {20250401, 9, 37218, 34154},
				        {20250401, 10, 42433, 50822},
				        {20250501, 6, 142762, 151125},
				        {20250501, 7, 72299, 74475},
				        {20250501, 8, 64116, 59421},
				        {20250501, 9, 33434, 35617},
				        {20250501, 10, 57812, 52869},
				        {20250601, 6, 156777, 157887},
				        {20250601, 7, 69889, 77585},
				        {20250601, 8, 53174, 62425},
				        {20250601, 9, 36174, 36874},
				        {20250601, 10, 62373, 54656},
				        {20250701, 6, 141282, 145236},
				        {20250701, 7, 69355, 72122},
				        {20250701, 8, 54188, 57454},
				        {20250701, 9, 32347, 33139},
				        {20250701, 10, 41866, 49398},
				        {20250801, 6, 152529, 145893},
				        {20250801, 7, 65187, 71139},
				        {20250801, 8, 73853, 57423},
				        {20250801, 9, 29348, 33372},
				        {20250801, 10, 57594, 49237},
				        {20250901, 6, 156186, 154625},
				        {20250901, 7, 77793, 76699},
				        {20250901, 8, 44239, 60259},
				        {20250901, 9, 37123, 35326},
				        {20250901, 10, 64845, 53328},
				        {20251001, 6, 164679, 160387},
				        {20251001, 7, 79654, 79826},
				        {20251001, 8, 80853, 62789},
				        {20251001, 9, 39641, 37784},
				        {20251001, 10, 57688, 54524},
				        {20251101, 6, 169895, 166428},
				        {20251101, 7, 84483, 82394},
				        {20251101, 8, 96829, 65486},
				        {20251101, 9, 37199, 38846},
				        {20251101, 10, 60651, 56734},
				        {20251201, 6, 202879, 173824},
				        {20251201, 7, 85374, 85295},
				        {20251201, 8, 77687, 68682},
				        {20251201, 9, 43669, 40335},
				        {20251201, 10, 54637, 59895}
				    },
				    Tabla = Table.FromRows(Semilla, {"FechaID", "CategoriaID", "Gastos", "Presupuesto"}),
				    ConID = Table.AddIndexColumn(Tabla, "GastoID", 1, 1, Int64.Type),
				    Tipado = Table.TransformColumnTypes(ConID, {
				        {"FechaID",     Int64.Type},
				        {"CategoriaID", Int64.Type},
				        {"Gastos",      type number},
				        {"Presupuesto", type number}
				    })
				in
				    Tipado

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

